files:
  include: '+(addon|app|tests)/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 0
  border-zero: 0
  brace-style: 2
  class-name-format: 2
  clean-import-paths: 2
  empty-args: 2
  empty-line-between-blocks: 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  final-newline: 2
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format: 0
  indentation: 2
  leading-zero: 2
  mixins-before-declarations: 2
  mixin-name-format: 2
  nesting-depth: 0
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format: 2
  property-sort-order:
    - 2
    -
      order: smacss
  property-units: 0
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 2
  variable-name-format: 2
  zero-unit: 2
